version: '3.8'

services:
  # Backend service (Node.js with Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hotel_sync_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/hotelsync_db  # Match this with config.js settings
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  # Frontend service (React with Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hotel_sync_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: hotel_sync_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hotelSync-local  # Match this with your database name in config.js
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
