version: '3.8'

services:
  # Backend service (Node.js with Express)
  backend:
    build:
      context: ./backend  # Build context should point to the backend directory at the root level
      dockerfile: Dockerfile
    container_name: hotel_sync_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/hotelsync_db  # Ensure this matches your config
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app  # Sync files between host and container

  # Frontend service (React with Vite)
  frontend:
    build:
      context: ./frontend  # Build context should point to the frontend directory at the root level
      dockerfile: Dockerfile  # Make sure this is the correct path
    container_name: hotel_sync_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend  # Mount the frontend directory to /frontend in the container
    working_dir: /frontend  # Set the working directory for the frontend container

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: hotel_sync_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hotelSync-local  # Ensure this matches your database name in config.js
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
