version: '3.8'

services:
  backend:
    build:
      context: .  # Ensure the context is the root of the project (not just ./backend)
      dockerfile: backend/Dockerfile  # Path to the Dockerfile from the root
    container_name: hotel_sync_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/hotelsync_db
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app  # Moun
