version: '3.8'

services:
  backend:
    build:
      context: ./  # Make sure the context points to the root folder
      dockerfile: backend/Dockerfile  # Ensure the correct Dockerfile is used
    container_name: hotel_sync_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/hotelsync_db
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: hotel_sync_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: hotel_sync_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotelsync_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
