version: '3.8'

services:
  # Backend service (Node.js with Express)
  backend:
    build:
      context: ./  # Build from the root directory
      dockerfile: backend/Dockerfile  # Specify the backend Dockerfile
    container_name: hotel_sync_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/hotelsync_db
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  # Frontend service (React with Vite)
  frontend:
    build:
      context: ./  # Build from the root directory
      dockerfile: frontend/Dockerfile  # Specify the frontend Dockerfile
    container_name: hotel_sync_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: hotel_sync_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotelsync_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
