version: "3.8"
services:
  backend:
    build:
      context: ./backend  # Ensure this points to the backend directory
    ports:
      - "3000:3000"

    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/hotelsync_db  # Ensure this matches your config
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app  # This will sync files between host and container

  # Frontend service (React with Vite)
  frontend:
    build:
      context: ./frontend  # Build context should point to the frontend directory at the root level
      dockerfile: Dockerfile
    container_name: hotel_sync_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # PostgreSQL service
  db:
    image: postgres:13
    container_name: hotel_sync_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=hotelSync-local  # Make sure this matches your database name in config.js
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
